language: node_js
node_js:
  - "stable"
script:
  - yarn run build
  - yarn run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master